// global-data.js
const songData = [
    { name: "Andha-Sooriyan", artist: "Ravi Bharath", album: "Aayathamaa Vol 1", lang: "Tamil", url: "/tamil-songs/ravi-bharath/Andha-Sooriyan.html" },
    { name: "Egipthilirunthu-Kaananukku", artist: "Ravi Bharath", album: "Aayathamaa Vol 1", lang: "Tamil", url: "/tamil-songs/ravi-bharath/Egipthilirunthu-Kaananukku.html" },
    { name: "Netru-Indru-Naalai", artist: "Ravi Bharath", album: "Aayathamaa Vol 1", lang: "Tamil", url: "/tamil-songs/ravi-bharath/Netru-Indru-Naalai.html" },
    { name: "Pidhavay-Potri", artist: "Ravi Bharath", album: "Aayathamaa Vol 1", lang: "Tamil", url: "/tamil-songs/ravi-bharath/Pidhavay-Potri.html" },
    { name: "Sthothiramae-Sthothiramae", artist: "Ravi Bharath", album: "Aayathamaa Vol 1", lang: "Tamil", url: "/tamil-songs/ravi-bharath/Sthothiramae-Sthothiramae.html" },
    { name: "Ulagam-Thondrum", artist: "Ravi Bharath", album: "Aayathamaa Vol 1", lang: "Tamil", url: "/tamil-songs/ravi-bharath/Ulagam-Thondrum.html" },
    { name: "Vaa-Endrazhaikum", artist: "Ravi Bharath", album: "Aayathamaa Vol 1", lang: "Tamil", url: "/tamil-songs/ravi-bharath/Vaa-Endrazhaikum.html" },
    { name: "Yaaridam-Solven", artist: "Ravi Bharath", album: "Aayathamaa Vol 1", lang: "Tamil", url: "/tamil-songs/ravi-bharath/Yaaridam-Solven.html" },
    { name: "Yesuvai-Nesikka-Thodanginaen", artist: "Ravi Bharath", album: "Aayathamaa Vol 1", lang: "Tamil", url: "/tamil-songs/ravi-bharath/Yesuvai-Nesikka-Thodanginaen.html" },
    { name: "Aayathamaa Aayathamaa", artist: "Ravi Bharath", album: "Aayathamaa Vol 1", lang: "Tamil", url: "/tamil-songs/ravi-bharath/Aayathamaa-Aayathamaa.html" },
    { name: "Sarva Valla Devan Peyar", artist: "Paul Thangiah", album: "Ven Puraavae Varuga", lang: "Tamil", url: "/tamil-songs/Sarva-Valla-Devan-Peyar.html" },
    { name: "Indiyavil Yesu Naamam", artist: "Paul Thangiah", album: "Ven Puraavae Varuga", lang: "Tamil", url: "/tamil-songs/Indiyavil-Yesu-Namam.html" },
    { name: "Yesu Raja Yelai", artist: "Berchmans", album: "JJ Vol 1", lang: "Tamil", url: "/tamil-songs/Berchmans/jj-vol-1/Yesu-Raja-Yelai.html" },
    { name: "Yaar Ennai Kaivittalum", artist: "Berchmans", album: "JJ Vol 1", lang: "Tamil", url: "/tamil-songs/Berchmans/jj-vol-1/Yaar-Ennai-Kaivittalum.html" },
    { name: "Ummodu Irukkanumae", artist: "Berchmans", album: "JJ Vol 1", lang: "Tamil", url: "/tamil-songs/Berchmans/jj-vol-1/Ummodu-Irukkanumae.html" },
    { name: "Thaedi Vantha Deivam Yesu", artist: "Berchmans", album: "JJ Vol 1", lang: "Tamil", url: "/tamil-songs/Berchmans/jj-vol-1/Thaedi-Vantha-Deivam-Yesu.html" },
    { name: "Singa Kuttigal", artist: "Berchmans", album: "JJ Vol 1", lang: "Tamil", url: "/tamil-songs/Berchmans/jj-vol-1/Singa-Kuttigal.html" },
    { name: "Nandri Nandri Nandri", artist: "Berchmans", album: "JJ Vol 1", lang: "Tamil", url: "/tamil-songs/Berchmans/jj-vol-1/Nandri-Nandri-Nandri.html" },
    { name: "Kiristhuvukkul Vaazhum Enakku", artist: "Berchmans", album: "JJ Vol 1", lang: "Tamil", url: "/tamil-songs/Berchmans/jj-vol-1/Kiristhuvukkul-Vaazhum-Enakku.html" },
    { name: "Isravaelae Bayapadathae", artist: "Berchmans", album: "JJ Vol 1", lang: "Tamil", url: "/tamil-songs/Berchmans/jj-vol-1/Isravaelae-Bayapadathae.html" },
    { name: "En Paavangal", artist: "Berchmans", album: "JJ Vol 1", lang: "Tamil", url: "/tamil-songs/Berchmans/jj-vol-1/En-Paavangal.html" },
    { name: "Adimai Naan Aandavarae", artist: "Berchmans", album: "JJ Vol 1", lang: "Tamil", url: "/tamil-songs/Berchmans/jj-vol-1/Adimai-Naan-Aandavarae.html" },
    { name: "Aandavarae Um Paatham", artist: "Berchmans", album: "JJ Vol 1", lang: "Tamil", url: "/tamil-songs/Berchmans/jj-vol-1/Aandavarae-Um-Paatham.html" },    
    { name: "Naan Bayapadavae Maataen", artist: "HMS", album: "Single", lang: "Tamil", url: "/tamil-songs/Naan-Bayapadavae-Maataen.html" },
    { name: "Urudhiyanadhu Unga Vaarthai", artist: "Ravi Bharath", album: "Aayathamaa Vol 8", lang: "Tamil", url: "/tamil-songs/Urudhiyanadhu-Unga-Vaarthai.html" },
    { name: "Yutham Seiya Purapaduvom", artist: "Paul Thangiah", album: "Abishaega Naathaa", lang: "Tamil", url: "/tamil-songs/Yutham-Seiya-Purapaduvom.html" },
    { name: "Yehova Shalom", artist: "Unknown", album: "Single", lang: "Tamil", url: "/tamil-songs/YEHOVA-SHALOM.html" },
    { name: "Nee Visvasa Navalo", artist: "Unknown", album: "Single", lang: "Telugu", url: "/telugu-songs/Nee-Visvasa-Navalo.html" },
    { name: "Azhaitheer Pinthodarnthaen", artist: "Praiselin Stephen", album: "Single", lang: "Tamil", url: "/tamil-songs/Azhaitheer-Pinthodarnthaen.html" },
    { name: "Nandri Solli Paaduven", artist: "Hema John", album: "Single", lang: "Tamil", url: "/tamil-songs/Nandri-solli-paaduven.html" },
    { name: "Uyaramum Unnathamumaana", artist: "Wesley Maxwell", album: "Single", lang: "Tamil", url: "/tamil-songs/Uyaramum-Unnathamumaana.html" },
    { name: "Thuthi Thuthi Yesuvai", artist: "Paul Thangiah", album: "Indhiya Enathu Vaanjai", lang: "Tamil", url: "/tamil-songs/Thuthi-Thuthi-Yesuvai.html" },
    { name: "En Nenapave Irupavare Yesayya", artist: "Anandharaj", album: "Single", lang: "Tamil", url: "/tamil-songs/En-Nenapave-Irupavare-Yesayya.html" },
    { name: "Oottru Thanneerae Enthan", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Oottru Thanneerae-Enthan.html" },
    { name: "Oppattra En Selvamae", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Oppattra-En-Selvamae.html" },
    { name: "Parisuthamae Paran Yesu", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Parisuthamae-Paran-Yesu.html" },
    { name: "Saronin Roja Ivar", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Saronin-Roja-Ivar.html" },
    { name: "Siluvayil Thongum Yesu", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Siluvayil-Thongum-Yesu.html" },
    { name: "Sonnapadi Uyirthelunthar", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Sonnapadi-Uyirthelunthar.html" },
    { name: "Sumanthu Kaakkum Yesuvidam", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Sumanthu-Kaakkum-Yesuvidam.html" },
    { name: "Ummai Nokki Parkkindraen", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Ummai-Nokki-Parkkindraen.html" },
    { name: "Unnathathin Aaviyai Unthan", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Unnathathin-Aaviyai-Unthan.html" },
    { name: "Yaar Pirikka Mudiyum En", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Yaar-Pirikka-Mudiyum-En.html" },
    { name: "Yaar Vaendum Naatha", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Yaar-Vaendum-Naatha.html" },
    { name: "Yesu Nam Pinigalai", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Yesu-Nam-Pinigalai.html" },
    { name: "Yesu Nammodu Indru", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Yesu-Nammodu-Indru.html" },
    { name: "Yesu Pothumae Enakku", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Yesu-Pothumae-Enakku.html" },
    { name: "Halleluiah Elshadai", artist: "Paul Thangiah", album: "Paraloga Devanae", lang: "Tamil", url: "/tamil-songs/paul-thangiah/Halleluia-Elshadai.html" },
    { name: "Deevinchave Samruddiga", artist: "Suhaas Prince", album: "Single", lang: "Telugu", url: "/telugu-songs/Deevinchave-Samruddiga.html" },
    { name: "Parisutha Aaviyai Ootridumae", artist: "Paul Thangiah", album: "Ven Puraave Varuga", lang: "Tamil", url: "/tamil-songs/paul-thangiah/Parisutha-Aaviyai-Ootridumae.html" },
    { name: "Neelone Anandham", artist: "Mark Ronald", album: "Single", lang: "Telugu", url: "/telugu-songs/Neelone-Anandham.html" },
    { name: "Emaina Cheyagalavu", artist: "Daniel Praneeth", album: "Single", lang: "Telugu", url: "/telugu-songs/Emaina-Cheyagalavu.html" },
    { name: "Adbhutam Cheyumaya", artist: "Paul Moses", album: "Unknown", lang: "Telugu", url: "/telugu-songs/Adbhutam-cheyumaya.html" },
    { name: "Hallelujah Sthuthi Mahima", artist: "Unknown", album: "Unknown", lang: "Telugu", url: "/telugu-songs/Hallelujah-Sthuthi-Mahima.html" },
    { name: "Kondaduvom Naam", artist: "Paul Thangiah", album: "Neer Vaendum", lang: "Tamil", url: "/tamil-songs/paul-thangiah/Kondaduvom-Naam.html" },
    { name: "Yesu Kristhu Aandavar", artist: "Paul Thangiah", album: "Indhiya Enathu Vaanjai", lang: "Tamil", url: "/tamil-songs/paul-thangiah/Yesu-Kristhu-Aandavar.html" },
    { name: "Unga Samugathilae", artist: "Bennet Christopher", album: "Single", lang: "Tamil", url: "/tamil-songs/general/Unga-Samugathilae.html" },
    { name: "Vedanin kanniku Thapinom", artist: "Berchmans", album: "Jebathotta Jeya Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/Vedanin-Kanniku-Thapinom.html" },
    { name: "Kaanikkai Thanthom Karthaavae", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Kaanikkai-Thanthom-Karthaavae.html" },
    { name: "Karam Pidithu Vazhinadathum", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Karam-Pidithu-Vazhinadathum.html" },
    { name: "Koopidum Kuralthanai Kaetu", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Koopidum-Kuralthanai-Kaetu.html" },
    { name: "Maritha Yesu Uyirthuvittar", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Maritha-Yesu-Uyirthuvittar.html" },
    { name: "Naalaya Thinathai", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Naalaya-Thinathai.html" },
    { name: "Naan Bayappadum Naalinilae", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Naan-Bayappadum-Naalinilae.html" },
    { name: "Naan Unnai Vittu Vilaguvathillai", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Naan-Unnai-Vittu-Vilaguvathillai.html" },
    { name: "Nandriyaal Thuthipaadu", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Nandriyaal-Thuthipaadu.html" },
    { name: "Kankalai Yeredupen", artist: "Paul Thangiah", album: "Indhiya Enathu Vaanjai", lang: "Tamil", url: "/tamil-songs/paul-thangiah/Kankalai-Yeredupen.html" },
    { name: "Enthan Yesu Kaividamaataar", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Enthan-Yesu-Kaividamaataar.html" },
    { name: "Eppadi Paaduvaen Naan", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Eppadi-Paaduvaen-Naan.html" },
    { name: "Ezhaigalin Belanae", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Ezhaigalin-Belanae.html" },
    { name: "Immattum Kaivida Devan", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Immattum-Kaivida-Devan.html" },
    { name: "Kaangindra Devan Nam Devan", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Kaangindra-Devan-Nam-Devan.html" },
    { name: "Kalangaathae Maganae Thigai", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Kalangaathae-Maganae-Thigai.html" },
    { name: "En Aathmaavum Sareeramum", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/En-Aathmaavum-Sareeramum.html" },
    { name: "En Maeipparae Yaesayya", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/En-Maeipparae-Yaesayya.html" },
    { name: "Engal Devan Vallavarae", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Engal-Devan-Vallavarae.html" },
    { name: "Engu Pogireer", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Engu-Pogireer.html" },
    { name: "Ennai Thaedi Yesu Vanthaar", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Ennai-Thaedi-Yesu-Vanthaar.html" },
    { name: "En Deivam Yesu", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/border-slate-200/En-Deivam-Yesu.html" },
    { name: "Devanae En Deva", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Devanae-En-Thaevaa.html" },
    { name: "Aa Alleluiah Sarva Vallavar", artist: "Paul Thangiah", album: "Uyirullavarai", lang: "Tamil", url: "/tamil-songs/paul-thangiah/Aa-Alleluiah-Sarva-Vallavar.html" },
    { name: "En Uyirulla Varai", artist: "Paul Thangiah", album: "Buyirullavarai", lang: "Tamil", url: "/tamil-songs/paul-thangiah/En-Uyirulla-Varai.html" },
    { name: "Ethai Ilanthaalum Ithai", artist: "Thomas", album: "Yaesuvai Paaduvom", lang: "Tamil", url: "/tamil-songs/general/Ethai-Ilanthaalum-Ithai.html" },
    { name: "Krupa Kaalamu Daati", artist: "Unknown", album: "Zion Gospel Songs", lang: "Telugu", url: "/telugu-songs/Krupa-Kaalamu-Daati.html" },
    { name: "Anbin Deivam Yesu", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Anbin-Deivam-Yesu.html" },
    { name: "Desamae Bayapadaathae", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Desamae-Bayapadaathae.html" },
    { name: "Appa Veetil Eppothum", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Appa-Veetil-Eppothum.html" },
    { name: "Appa Naan Ummai Paarkindraen", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Appa-Naan-Ummai-Paarkindraen.html" },
    { name: "Aandavar Enakkai", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Aandavar-Enakkai-Yaavaiyum.html" },
    { name: "Visuvaasathinaal Neethimaan", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Visuvaasathinaal-Neethiman.html" },
    { name: "Ennai Undaakkiya En", artist: "Berchmans", album: "Visuvaasa Geethangal", lang: "Tamil", url: "/tamil-songs/berchmans/visuvaasa-geethangal/Ennai-Undaakkiya-En-Thaevaathi.html" },
    { name: "Uyirodu Ezhunthavarae", artist: "Paul Thangiah", album: "Pugal Esuvukae", lang: "Tamil", url: "/tamil-songs/paul-thangiah/Uyirodu-Ezhunthavarae-Ummai.html" },
    { name: "Jeevikindravarae", artist: "Sijanth", album: "Single", lang: "Tamil", url: "/tamil-songs/sijanth/Jeevikindravarae.html" },
    { name: "Jeba Sinthai Enil Thaarum", artist: "Traditional", album: "Hymns", lang: "Tamil", url: "/tamil-songs/general/Jeba-Sinthai-Enil-Thaarum.html" },
    { name: "Yesuve Neere Enthan", artist: "Paul Thangiah", album: "Single", lang: "Tamil", url: "/tamil-songs/paul-thangiah/Yesuve-Neere-Enthan.html" },
    { name: "Vaethanai En Valvil", artist: "Paul Thangiah", album: "Single", lang: "Tamil", url: "/tamil-songs/paul-thangiah/Vaethanai-En-Valvil.html" },
    { name: "Yaega Sinthaiyae", artist: "Aaron Samuel", album: "Single", lang: "Tamil", url: "/tamil-songs/general/Yega-Sinthaye-Yega-Snegame.html" },
    { name: "Vazhvin Aadharamae", artist: "Alwin Thomas", album: "Nandri", lang: "Tamil", url: "/tamil-songs/general/Vazhvin-Aadharamae.html" },
    { name: "Nannalli Vasisuveya", artist: "Jacob Bhushan", album: "Single", lang: "Telugu", url: "/telugu-songs/Nannalli-Vasisuveya.html" },
    { name: "Prabhu Na Papamulanu", artist: "Gowtam Israel", album: "Single", lang: "Telugu", url: "/telugu-songs/Prabhu-Na-Papamulanu.html" }
];

window.handleHeaderSearch = function(event) {
    if (event.key === 'Enter') {
        const query = encodeURIComponent(event.target.value.trim());
        const localSearch = document.getElementById('songSearch');
        if (localSearch) {
            localSearch.value = event.target.value;
            if (typeof renderSongs === 'function') renderSongs();
        } else {
            window.location.href = '/?search=' + query;
        }
    }
};